spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${url}
    username: ${dbusername}
    password: ${dbpwd}
    hikari:
      connection-timeout: 60000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 30
      minimum-idle: 10
      read-only: false
  redis:
    host: ${redisip}
    port: ${redisport}
    database: 0
    password: ${redispwd}
    connect-timeout: 3s
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0

# 本机配置
file:
  staticPath: http://www.xxx.com
  staticPatternPath: /upimages/**
  uploadFolder: /tmp